apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::428362520565:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-W4C07L9OF72X
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::428362520565:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-12T09:10:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-12T09:10:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1377"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: aacb2524-a331-4bd8-982d-11610505a621
